services:
  source_postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: source_db
    ports:
      - "5433:5432"
    networks:
      - elt_network
    volumes:
      - ./source_database/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    image: postgres:15
    ports:
      - 5434:5432
    networks:
      - elt_network    
    depends_on:
      - source_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: destination_db

    # volumes:
    #   - destination_db_data:/var/lib/postgresql/data
    
  elt_script:
    build:
      context: ./ELT_SCRIPT
      dockerfile: Dockerfile
    command: ["python", "elt_script.py"]
    networks:
      - elt_network
    depends_on:
      - destination_postgres
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.4.7

    command: [
               "run",
               "--profiles-dir",
               "/root",
               "--project-dir",
               "/dbt"
               ]
    networks:
      - elt_network     
    volumes:   
      - ./transformation_database_project:/dbt
      - ~/.dbt:/root
    depends_on:
      - elt_script
    environment:
      DBT_PROFILES: default
      DBT_TARGET: dev

networks:
  elt_network:
    driver: bridge


volumes:
  destination_db_data: