services:  
  source_postgres:          
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret      
    volumes:
      - ./source_db/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    networks:
      - elt_network
    depends_on:
      - source_postgres
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      
  elt_script:   
    build:
      context: ./script_elt
      dockerfile: Dockerfile
    command: ["python", "script.py"]
    networks:
      - elt_network
    depends_on:
      - source_postgres 
      - destination_postgres
networks:
  elt_network:
    driver: bridge




